# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - new-smart-crm-backend

on:
  # Disabled - using deploy-app.yml instead
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          cd apps/backend
          npm ci
          npm run build
          npm test --if-present

      - name: Prepare deployment package
        run: |
          cd apps/backend
          # Create a clean deployment directory
          mkdir -p deployment
          # Copy dist contents to deployment root
          cp -r dist/* deployment/
          # Copy package.json to deployment root
          cp package.json deployment/
          # Install production dependencies
          npm ci --only=production
          # Copy node_modules to deployment
          cp -r node_modules deployment/
          # Create deployment package from deployment directory
          cd deployment
          zip -r ../../../release.zip ./*
          cd ../..
          
          # Verify deployment package structure
          echo "🔍 Verifying deployment package structure..."
          unzip -l release.zip | head -20
          echo "✅ Deployment package created successfully"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F117B4BEB76948F4BA6423ECFB4145F4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2D24B2AB32944A969083FDFE672FB506 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7177CF2DF9E84D9DAA9C47B129D7FAA7 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'new-smart-crm-backend'
          slot-name: 'dev'
          package: .
          startup-command: 'npm run start:prod'
          